### ISSUE TITLE
Error when configuring KNI interfaces: fail to execute command OP_ADD_ETHER_ADDRESS

### ISSUE THREAD

**Issue by yoooou** [omec-project/omec-project-ci#28]
**Issue**:

DP gives the following error when trying to bring up S1Udev or SGIdev interfaces:

> i40evf_add_del_all_mac_addr(): fail to execute command OP_ADD_ETHER_ADDRESS

And syslog on the host machine gives

> i40e 0000:1c:00.0: VF is not trusted, switch the VF to trusted to add more functionality
i40e 0000:1c:00.0: VF 0 failed opcode 10, retval: -1

And DP won’t be able to receive any packets.

**Setup**:

- SR-IOV configured on two X710 NICs and VFs configured by [sriov.sh](https://github.com/clearlinux/cloud-native-setup/blob/master/clr-k8s-examples/9-multi-network/systemd/sriov.sh) (also turned off spoof check):

> 3: enp28s0f0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq portid 3cfdfea7c948 state UP mode DEFAULT group default qlen 1000
    link/ether 3c:fd:fe:a7:c9:48 brd ff:ff:ff:ff:ff:ff
    vf 0 MAC 8a:42:b8:a4:92:c8, spoof checking off, link-state enable
    vf 1 MAC c6:60:8f:79:94:b1, spoof checking off, link-state enable

> 11: enp216s0f0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq portid 3cfdfea7c268 state UP mode DEFAULT group default qlen 1000
    link/ether 3c:fd:fe:a7:c2:68 brd ff:ff:ff:ff:ff:ff
    vf 0 MAC a2: ab:f7:1d:0a:ed, spoof checking off, link-state enable
    vf 1 MAC 52:86:7e:3e:80:4b, spoof checking off, link-state enable

and topology looks like following:

TrafficGen-generator -> NIC0-VF1 -> NIC0-VF0 -> DP-S1u -> DP-SGi -> NIC1-VF0 -> NIC1-VF1 -> TrafficGen-responder

- Host passthrough is configured for both DP and TrafficGen VMs

- Interfaces are bind to gib_uio by dpdk-devbind.py

- dp_config.cfg is configured with correct PORT and MAC for S1U and SGI

**Comment by krsna1729** [comment]
@micpez is there documentation of the CI VMs setup

**Comment by micpez** [comment]
Not that I am aware of, the setup was given.

**Comment by micpez** [comment]
@yoooou  do you have the output of dpdk-devbind.py --status and the full dp log where the error is visible?

**Comment by yoooou** [comment]
> Network devices using DPDK-compatible driver
============================================
0000:00:07.0 'Ethernet Virtual Function 700 Series 154c' drv=igb_uio unused=i40evf
0000:00:09.0 'Ethernet Virtual Function 700 Series 154c' drv=igb_uio unused=i40evf

> Network devices using kernel driver
===================================
0000:00:03.0 'RTL-8100/8101L/8139 PCI Fast Ethernet Adapter 8139' if=ens3 drv=8139cp unused=8139too,igb_uio *Active*
0000:00:08.0 'Virtio network device 1000' if=ens8 drv=virtio-pci unused=igb_uio *Active*

[dp.log](https://github.com/omec-project/omec-project-ci/files/3087216/dp.log)

Please let me know if you need any other information. Thanks @micpez

**Comment by krsna1729** [comment]
@omec-project/tst we currently do not have documentation on CI setup. @micpez @yoooou should we rename this issue asking for documentation or open another issue?

**Comment by krsna1729** [comment]
when i say CI setup i mean VMs (CP/DP/HSS/HSSDB etc.,) used for testing.

Please note that we are recycling the VM environment across builds, which may hide any manual additions at system level not captured since we are not testing from a clean slate.

**Comment by micpez** [comment]
> 
> Please let me know if you need any other information. Thanks @micpez

@yoooou Comparing your log with output of tc1 / tc2 test cases, seems that your DP is compiled with STATIC_ARP and you are also using kni. Do not know if this can explain your issue.

**Comment by yoooou** [comment]
@micpez Thanks for looking into the issue. It gives the same error by removing STATIC_ARP config
Looks like setting VF as trusted is not supported by the current kernel version (which is the same as the CI server). I can try upgrading it but just wondering why the CI environment doesn't have this issue.

**Comment by micpez** [comment]
@yoooou, you get the error when you run kni-S1Udevcfg.sh or kni-SGIdevcfg.sh?

**Comment by yoooou** [comment]
@micpez Yes kni-S1Udevcfg.sh and kni-SGIdevcfg.sh trigger the error

**Comment by yoooou** [comment]
@micpez @krsna1729 The problem went away after I upgraded kernel to 4.4.1 (from 4.4.0.131). With this kernel version I don’t see any errors and DP is showing some traffic

>  UPLINK                            ||                 DOWNLINK
IfMisPKTS    IfPKTS     UL-RX     UL-TX    UL-DFF   || IfMisPKTS    IfPKTS     DL-RX     DL-TX    DL-DFF
        0         0         0         0         0   ||         0         0         0         0         0
        0     95383     94689         0     94689   ||         0       695         0         0         0
        0    100800    100032         0    100032   ||         0       768         0         0         0

The traffic is not passing through though. But it’s the same thing when I run it *without* dpdk binding so I guess the problem is now somewhere else.
