### ISSUE TITLE
Rebasing on master during tests means that code under test differs from contents of patchset

### ISSUE THREAD

**Issue by zdw** [omec-project/omec-project-ci#40]
Currently the tests rebase the pull request on the master code, which means the test is happening on code that could be different than what was checked in.

It would be confusing if a developer tested locally and had success, then after creating a PR it failed because it was combined with other code.

Also, a rebase or merge could conflict, which would result in the tests not being run.

Recommend that we change to:

1. Test just the code just as it is checked in (no rebase)
2. Require that code be rebased and squashed into a single commit on the HEAD of master prior to being merged.

**Comment by krsna1729** [comment]
1. Wasteful to run the test without a rebase. Better to gate it saying needs rebase.
2. A PR should be allowed to have multiple commits if it helps grouping changes to achieve the intent. So this should not be dictated in automation. It should be decided on a per PR basis by the maintainers

**Comment by zdw** [comment]
@krsna1729 I'm not sure if there's a way to have Github require that code is rebased on current HEAD of branch before testing.  This may need to be scripted as the first step of the test.

Using multiple commits to group changes seems fine.  Do we want to require that multiple commits are squashed into one before merge?

**Comment by krsna1729** [comment]
Guess we can add it as first step.

No we want them to stay separate and we'll use "rebase and merge" button. This way the separation is reflected in the git history too and not just in github PR page.

**Comment by micpez** [comment]
> Guess we can add it as first step.

@zdw, @krsna1729 , could you please clarify what is needed compared to current status?
rebase of PR on master is already implemented and test fails if rebase fails (when can improve the error  message if needed).

**Comment by krsna1729** [comment]
I think it's mostly fine the way it is now. To remove confusion for the developer we can say there was a rebase that was done in a more prominent way, if the test fails?

**Comment by zdw** [comment]
If the user has to do the rebase, they can deal with merge conflicts and other issues manually, whereas the current automation it isn't guaranteed to succeed.

What I'm suggesting is that the test should verify in git history that the patchsets is based on current master, and fail fast if that's not the case.

Fundamentally the PR review and tests should be on the code as shown in the PR, not of an automated amalgamation that could change or fail if other PR's were merged before/after the tests occurred.

**Comment by micpez** [comment]
@zdw, @krsna1729 hope this is in line with above.

**Comment by micpez** [comment]
@zdw, @krsna1729 One thought. In this way it is demanded to always rebase patches.
Not sure what is the requirement, if patches should be always rebased or merged instead.
A alternative option could be:
1. clone repo
2. merge with master
3.fail immediately if there are merge-conflicts or test
